version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MY_VAR_EXAMPLE=example
      - APP_PORT=5000
    volumes:
      - .:/app
    restart: unless-stopped 