version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MY_VAR_EXAMPLE=example
      - APP_PORT=3000
    volumes:
      - .:/app
    restart: unless-stopped 